// src/Domains/_shared/DomainErrorCode.ts
//
// Satu-satunya sumber kebenaran untuk semua kode error domain di project ini.
// Dipakai oleh:
// 1. Entities (Domains/) saat throw new Error(DomainErrorCode.XXX)
// 2. Validators (Infrastructures/validation/) saat mendefinisikan pesan error Zod
// 3. DomainErrorTranslator (Commons/exceptions/) sebagai key penerjemahan
//
// Karena ketiganya merujuk objek yang SAMA, typo di salah satu sisi akan
// langsung ditolak TypeScript saat compile, bukan baru ketahuan saat runtime.

export const DomainErrorCode = {
    // ============ AUTHENTICATIONS ============
    ACCESS_TOKEN_INVALID: "ACCESS_TOKEN.INVALID",
    ACCESS_TOKEN_MISSING: "ACCESS_TOKEN.MISSING",

    // ============ ALBUMS ============
    ALBUM_NOT_CONTAIN_NEEDED_PROPERTY: "ALBUM.NOT_CONTAIN_NEEDED_PROPERTY",
    ALBUM_NOT_MEET_DATA_TYPE_SPECIFICATION: "ALBUM.NOT_MEET_DATA_TYPE_SPECIFICATION",
    ALBUM_YEAR_CANNOT_BE_IN_THE_FUTURE: "ALBUM.YEAR_CANNOT_BE_IN_THE_FUTURE",
    ALBUM_NOT_FOUND: "ALBUM.NOT_FOUND",

    // ============ SONGS ============
    SONG_NOT_CONTAIN_NEEDED_PROPERTY: "SONG.NOT_CONTAIN_NEEDED_PROPERTY",
    SONG_NOT_MEET_DATA_TYPE_SPECIFICATION: "SONG.NOT_MEET_DATA_TYPE_SPECIFICATION",
    SONG_YEAR_CANNOT_BE_IN_THE_FUTURE: "SONG.YEAR_CANNOT_BE_IN_THE_FUTURE",
    SONG_NOT_FOUND: "SONG.NOT_FOUND",

    // ============ PLAYLISTS ============
    PLAYLIST_PARAMS_NOT_MEET_DATA_TYPE_SPESIFICATION: "PLAYLIST_PARAMS.NOT_MEET_DATA_TYPE_SPESIFICATION",
    PLAYLIST_NOT_CONTAIN_NEEDED_PROPERTY: "PLAYLIST.NOT_CONTAIN_NEEDED_PROPERTY",
    PLAYLIST_NOT_MEET_DATA_TYPE_SPECIFICATION: "PLAYLIST.NOT_MEET_DATA_TYPE_SPECIFICATION",
    PLAYLIST_NOT_FOUND: "PLAYLIST.NOT_FOUND",
    PLAYLIST_ACCESS_FORBIDDEN: "PLAYLIST.ACCESS_FORBIDDEN",

    // ============ PLAYLIST SONGS ============
    PLAYLIST_SONG_NOT_CONTAIN_NEEDED_PROPERTY: "PLAYLIST_SONG.NOT_CONTAIN_NEEDED_PROPERTY",
    PLAYLIST_SONG_NOT_MEET_DATA_TYPE_SPECIFICATION: "PLAYLIST_SONG.NOT_MEET_DATA_TYPE_SPECIFICATION",
    PLAYLIST_SONG_ALREADY_EXISTS: "PLAYLIST_SONG.ALREADY_EXISTS",
    PLAYLIST_SONG_NOT_FOUND: "PLAYLIST_SONG.NOT_FOUND",

    // ============ COLLABORATIONS ============
    COLLABORATION_NOT_CONTAIN_NEEDED_PROPERTY: "COLLABORATION.NOT_CONTAIN_NEEDED_PROPERTY",
    COLLABORATION_NOT_MEET_DATA_TYPE_SPECIFICATION: "COLLABORATION.NOT_MEET_DATA_TYPE_SPECIFICATION",
    COLLABORATION_ALREADY_EXISTS: "COLLABORATION.ALREADY_EXISTS",
    COLLABORATION_NOT_FOUND: "COLLABORATION.NOT_FOUND",
    COLLABORATION_ACCESS_FORBIDDEN: "COLLABORATION.ACCESS_FORBIDDEN",

    // ============ ALBUM LIKES ============
    ALBUM_LIKE_ALREADY_EXISTS: "ALBUM_LIKE.ALREADY_EXISTS",
    ALBUM_LIKE_NOT_FOUND: "ALBUM_LIKE.NOT_FOUND",

    // ============ EXPORTS ============
    EXPORT_NOT_CONTAIN_NEEDED_PROPERTY: "EXPORT.NOT_CONTAIN_NEEDED_PROPERTY",
    EXPORT_NOT_MEET_DATA_TYPE_SPECIFICATION: "EXPORT.NOT_MEET_DATA_TYPE_SPECIFICATION",
    EXPORT_TARGET_EMAIL_INVALID: "EXPORT.TARGET_EMAIL_INVALID",

    // ============ UPLOADS ============
    UPLOAD_COVER_IMAGE_TYPE_NOT_ALLOWED: "UPLOAD_COVER.IMAGE_TYPE_NOT_ALLOWED",
    UPLOAD_COVER_SIZE_EXCEEDS_LIMIT: "UPLOAD_COVER.SIZE_EXCEEDS_LIMIT",
    UPLOAD_COVER_FILE_MISSING: "UPLOAD_COVER.FILE_MISSING",

    // =========== AUTHORIZATION ===========
    USER_NOT_AUTHORIZED_TO_USE_THIS_ACTION: "USER.NOT_AUTHORIZED_TO_USE_THIS_ACTION",
    USER_NOT_FOUND: "USER.NOT_FOUND",
} as const;

export type DomainErrorCode = (typeof DomainErrorCode)[keyof typeof DomainErrorCode];